### ISSUE TITLE
Yarn is not being installed

### ISSUE THREAD

**Issue by ChFlick** [Siouan/frontend-gradle-plugin#74] opened 2020-03-04 09:07 UTC
Hi,

in my Project I have yarnEnabled = true, but the yarn install step is skipped and I get the error that the yarn executable is not found.

Here the result of `gradle installFrontend --info`:
```
Initialized native services in: /home/chris/.gradle/native
The client will now receive all logging from the daemon (pid: 411). The daemon log file: /home/chris/.gradle/daemon/6.1.1/daemon-411.out.log
Starting 7th build in daemon [uptime: 27 mins 8.503 secs, performance: 100%, non-heap usage: 25% of 268.4 MB]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '.../settings.gradle'.
Projects loaded. Root project using build file '.../build.gradle'.
Included projects: [root project 'traffic-ui']

> Configure project :
Evaluating root project 'traffic-ui' using build file '.../build.gradle'.
All projects evaluated.
Selected primary task 'installFrontend' from project :
Tasks to be executed: [task ':installNode', task ':installFrontend']
:installNode (Thread[Execution worker for ':',5,main]) started.

> Task :installNode UP-TO-DATE
Caching disabled for task ':installNode' because:
  Build cache is disabled
Skipping task ':installNode' as it is up-to-date.
:installNode (Thread[Execution worker for ':',5,main]) completed. Took 0.061 secs.
:installFrontend (Thread[Execution worker for ':',5,main]) started.

> Task :installFrontend FAILED
Caching disabled for task ':installFrontend' because:
  Build cache is disabled
Task ':installFrontend' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:installFrontend (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installFrontend'.
> org.siouan.frontendgradleplugin.core.ExecutableNotFoundException: Yarn

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 761ms
2 actionable tasks: 1 executed, 1 up-to-date
```

When manually executing installYarn it is simply skipped:  
```
10:00:30: Executing task 'installYarn'...

> Task :installYarn SKIPPED

BUILD SUCCESSFUL in 299ms
10:00:30: Task execution finished 'installYarn'.
```

`> org.siouan.frontendgradleplugin.core.ExecutableNotFoundException: Yarn`

**Expected behavior**
Yarn should be installed and used.

**To Reproduce**
1. Put these settings in `build.gradle`:
```
plugins {
    id 'java'
    id 'org.siouan.frontend' version '1.3.0'
}

repositories {
    mavenLocal()
    mavenCentral()
}

group 'de.flick'
version '1.0.0-SNAPSHOT'

frontend {
    nodeVersion = '12.6.0'
    yarnEnabled = true
    yarnVersion = '1.22.0'
    cleanScript = 'run clean'
    assembleScript = 'run assemble'
    checkScript = 'run check'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
```
2. Execute the Gradle task `installFrontend`
3. See error/issue

**Environment (please complete the following information):**
 - OS: Manjaro Linux 19.0.2
 - JDK: OpenJDK Java 13
 - Gradle: Tested with 6.0.1 and 6.1.1
 - Frontend Gradle plugin: 1.3.0

**Additional context**
I also tried manually setting the yarnInstallDirectory (`yarnInstallDirectory = "${projectDir}/yarn"`), but it failed: 
```
> Cannot set the value of extension 'frontend' property 'yarnInstallDirectory' of type java.io.File using an instance of type org.codehaus.groovy.runtime.GStringImpl.
```

**Comment by vboriesazeau** [comment] 2020-03-09 14:20
Hi @ChFlick,
Thank you for your message.
I wasn't able to reproduce this issue, starting with an empty directory, and I don't have an idea why the task would be skipped by Gradle.
- Does the directory `${projectDir}/yarn` exists? Does it contain a `yarn` executable?
- Can you confirm the result when applying the steps above starting with an empty directory?
- Could you run command `gradle installYarn -d` and provide the result in this issue?

Thank you for your help!
BR,
Vincent

**Comment by ckosloski** [comment] 2020-03-09 17:03
For the `of type java.io.File using an instance of type org.codehaus.groovy.runtime.GStringImpl.` error, it looks like you have to make it a file:
`yarnInstallDirectory = file("${projectDir}/yarn")`

I also see the installYarn skipped issue.
The yarn directory is there and empty.

```2020-03-09T11:34:16.134-0500 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :installYarn SKIPPED
2020-03-09T11:34:16.134-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :installYarn' started
2020-03-09T11:34:16.134-0500 [INFO] [org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter] Skipping task ':installYarn' as task onlyIf is false.
2020-03-09T11:34:16.134-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :installYarn'
2020-03-09T11:34:16.135-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :installYarn' completed
```

**Comment by ChFlick** [comment] 2020-03-09 17:23
Thanks for your response @vboriesazeau.
 
- The directory `${projectDir}/yarn` does not exisit
- It works without a problem with a new project from scratch

[Here](https://github.com/Siouan/frontend-gradle-plugin/files/4308052/installYarn.log) is the log of `gradle installYarn -d`. I hope it helps you to find the problem. 

@ckosloski: `yarnInstallDirectory = file("...")` works fine, thanks!

**Comment by vboriesazeau** [comment] 2020-03-09 17:43
@ChFlick and @ckosloski, thanks for your help.
- Regarding the `yarnInstallDirectory` property, you're both right. The problem was already identified in issue #70. Documentation will be fixed in the next release.
- I ran the `installYarn` task with an existing empty `yarn` directory, and now I could reproduce the issue at the first execution. But subsequent tests don't produce the same result. I guess I have to understand better how the Gradle daemon works and manages output directories, because now, if I delete the `.gradle` and `build` directory of my empty project, and restart with an empty `yarn` directory, the task is not skipped anymore.

I must be confusing with Gradle behavior and/or `@OutputDirectory` annotation usage in the plugin code. But now I have a starting point to fix this issue.
Thanks again.
Vincent

**Comment by vboriesazeau** [comment] 2020-03-11 09:26
@ChFlick
Now I'm facing a new problem with this issue. I'm unable to reproduce it anymore. I thought I found the exact case when we discussed it some days ago, but unfortunately I didn't succeed to get the same result one more time.
It seems to me the issue highly depends on the steps executed before the final `installYarn` task that is skipped. By 'steps', I mean execution of other tasks in the same or different Gradle build, and the configuration changes applied on the timeline.
Can you share an archive of a project where the issue invariably appears?
If not, how did you work around with it?

@ckosloski
You mentioned you got the same issue: can you also share a process to reproduce it invariably?

For the moment, as a workaround, I can only suggest to delete the relevant `yarn` installation directory, which should allow to restore an 'understandable' state if the task `installYarn` is executed again.
Sorry for the inconvenience, and thanks again for your help.
BR,
Vincent

**Comment by ChFlick** [comment] 2020-03-11 11:13
It works consistently for the project I'm working at, I just created a separate branch for the yarn issue: https://github.com/ChFlick/connected-vehicle-microservice/tree/useYarn.  
Just clone it, `cd traffic-ui`, and then `./gradlew build` and the issue should occur.

As there is no yarn folder in my project, I just switched to npm as workaround.

**Comment by vboriesazeau** [comment] 2020-03-11 12:23
Thank you very much!

**Comment by vboriesazeau** [comment] 2020-03-11 14:20
Below is the analysis of the issue:

- The `gradlew build` command fails because the `installFrontend` task does not find the `yarn` executable in the default installation directory `${projectDir}/yarn`.
- The `installYarn` task is in charge of downloading and installing the Yarn distribution, if the `yarnEnabled` property is `true` in the project `build.gradle` file (which is the case here).
- When the `yarnEnabled` property is `true`, the `installYarn` task fails if the `yarnVersion` property is not defined. Consequently, the build should never reach the `installFrontend` task..

The problem here is the `installYarn` task is not executed because there's a bug in the plugin that disables this task. Validation rules are not checked, and the build is allowed to reach the `installFrontend` task. This one fails as expected because the Yarn distribution was not installed.

The fix will be available in the next release.
Apart from this issue, be careful because the `build.gradle` file contains an invalid configuration for the plugin: Yarn is enabled but the `yarnVersion` property is not defined.
Thanks again for your assistance!
BR,
Vincent

**Comment by ckosloski** [comment] 2020-03-11 14:24
I do have the `yarnVersion` set though
```
frontend {
    nodeVersion = '12.13.1'
    yarnEnabled = true
    yarnVersion = '1.19.2'
    yarnInstallDirectory = file("${projectDir}/yarn")
    // See 'scripts' section in your 'package.json file'
    cleanScript = 'run clean'
    assembleScript = 'run assemble'
    checkScript = 'run check'
}
```

**Comment by ChFlick** [comment] 2020-03-12 09:50
Thank you very much for your work @vboriesazeau :tada:

**Comment by vboriesazeau** [comment] 2020-03-12 13:32
@ckosloski,
The issue itself is not related to the `yarnVersion` property, but thank you about your remark that avoids misunderstandings!
If the fix in the next release doesn't solve the issue in your case, do not hesitate to reopen this discussion.
BR,
Vincent

**Closed** 2020-03-13 08:31 UTC
Labels: Bug
