### ISSUE TITLE
Support Yarn 2

### ISSUE THREAD

**Issue by pmwmedia** [siouan/frontend-gradle-plugin#139] opened 2020-11-26 13:49 UTC
Hi,

Do have any plans to support yarn 2?

Settings in `build.gradle` file:
```groovy
frontend {
    yarnVersion = '2.3.3'
}
```

**Comment by v1nc3n4** [comment] 2020-11-26 21:23
Hi,

This is a very good question. You have probably noticed the plugin explicitly states that it does not support Yarn 2, and by now, it was not a thoughtless remark.
In fact, my personal feeling with Yarn 2 is bad, regarding how I could support it with the plugin. I don't understand its installation process. I don't understand why [everyone must install Yarn 1 globally first, then set version 2 locally in the project](https://yarnpkg.com/getting-started/install#per-project-install), it is not what I call a per-project installation. The [migration guide](https://yarnpkg.com/getting-started/migration#step-by-step) is not better. There's no distribution to download, no way to explode an archive in a directory on a workstation where everything is protected against write access. There are many articles stating global install with NPM is bad practice. I pray of course to be ignorant or misunderstanding, because I agree it would be great to support it. Honestly, Yarn 2's documentation is so terrible to me.

> Do have any plans to support yarn 2?

No. But your question makes completely sense, and your need is an opportunity to improve 🤧. Actually, my availability is not good. Small issues remaining should be fixed before end of the year. If I expect many breaking changes and important effort on documentation, an approximative and reasonnable due date would be mid-2021. Maybe it requires little work. I would be very happy to support it sooner.

Do you have any feedback about Yarn 2 installation process so as I could reassure myself?
Feel free to share any personal experience with Yarn 2.
BR

**Comment by pmwmedia** [comment] 2020-11-26 21:53
I totally agree that the installation process of Yarn 2 is too cumbersome and especially not as easy to automate as I need for my build server. I have invested some time in the migration. However, I have finally decided to stick with the classic Yarn 1 for now.

So, my hope was to automate the installation of Yarn 2 in the future using the Gradle plugin.

**Comment by v1nc3n4** [comment] 2020-11-27 16:49
Hi @pmwmedia,

FYI, I took a look at the install process from scratch. I can confirm it will require some noticeable changes in the plugin, **but** it appears to me feasible now, at least for simple use cases. For example:

1. If the Node distribution is controlled by the plugin (`nodeDistributionProvided` is `false`), and if this distribution is not used by unrelated projects, it is fine to make a global install of Yarn Classic, and initiate Yarn 2 installation in the project.
1. In other cases, this global install might have impacts in unrelated projects (?), and seems risky to me.

Also I can highlight already:

- `yarnDistribution*` properties and `proxy*` properties will become unrelevant when Yarn 2 is used because the responsibility to download and install the distribution is handled by Yarn itself and settings in the `.yarnrc.yml` file.

Let's plan a first version to support Yarn 2 in the first case above and improve things little by little.
Have a nice week-end.
BR

**Comment by pmwmedia** [comment] 2020-11-27 19:18
Hi @v1nc3n4,

This sounds very promising :) I cannot await to test it!

Have a great weekend!

**Comment by UgmaDevelopment** [comment] 2021-01-29 16:49
@v1nc3n4, thanks for your work on this!

**Comment by v1nc3n4** [comment] 2021-03-07 13:56
Hi all,
Just to share with you a status about this issue.
I would say half of the work is done. An important rework of automated integration tests and documentation is now in progress.
I think mid of 2021 still is a relevant release date.
Thanks again for your patience.
BR

**Closed** 2021-11-07 17:45 UTC
Labels: Feature, DONE

**Comment by v1nc3n4** [comment] 2021-11-07 18:03
Hi all,
Release 6.0.0 now provides a first support of Yarn 1 and Yarn 2+ using the Berry baseline.
Feel free to provide any feedback by creating a new issue.
Thanks again for your patience.
BR
