### ISSUE TITLE
Execution failed for platform aarch64

### ISSUE THREAD

**Issue by apo1967** [siouan/frontend-gradle-plugin#148] opened 2021-02-02 14:09 UTC
Hi everyone, 

first of all thx for this great plugin.

I just tried to build my current project on my new MBP with M1 chip. It's a multi module Gradle projects containing a Spring Boot backend and Vue.js 2 frontend module. Unfortunately the build fails with the following error:

FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':frontend:installNode'.
> org.siouan.frontendgradleplugin.domain.exception.UnsupportedPlatformException: This platform is not supported yet: Platform {jvmArch=aarch64, osName=Mac OS X, environment=Environment {nodeInstallDirectory=null, yarnInstallDirectory=null}, systemProxySettings=SystemProxySettings {httpProxyHost=null, httpProxyPort=80, httpsProxyHost=null, httpsProxyPort=443, nonProxyHosts=[local, *.169.254/16, *.local, 169.254/16]}}
```

OS Mac Os X Big Sur 11.2
Gradle Version 6.7.1
Java Version 

```
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment Zulu15.29+15-CA (build 15.0.2+7)
OpenJDK 64-Bit Server VM Zulu15.29+15-CA (build 15.0.2+7, mixed mode)
```

Is there any chance this will be gonna be fixed soon?

Cheers,
Alexander

**Comment by v1nc3n4** [comment] 2021-02-02 14:42
Hi @apo1967,

Thank you for raising this issue! It shall be possible to fix it quickly, since it is just a matter of resolving the Node.js distribution compatible with your workstation's architecture (ARMv8 / Aarch64).

I need the following pieces of information of your Gradle project:
- Plugin version
- Node.js version

As a workaround, you may succeed to install Node.js with the plugin with this setting:
```.groovy
frontend {
    nodeDistributionUrlPathPattern = 'vVERSION/node-vVERSION-linux-arm64.TYPE'
}
```
If you can try this, let me know the result! Have a nice day.
Regards

**Comment by apo1967** [comment] 2021-02-02 15:14
Hi v1nc3n4,

thx for the quick response. The project node version is v15.4.0. The plugin version was 
```
plugins {
    id 'org.siouan.frontend-jdk11' version '4.0.1'
}

```

I upgraded to 5.0.0, but it did not make a difference.

The fix above does not help unfortunately. The error is the same.

Thanks very much,
Alexander

**Comment by v1nc3n4** [comment] 2021-02-02 15:40
That's perfect, thank you.
The fact that the issue is still there when forcing the URL means there is another bug because it should work. I create another issue for this one.
It shall be fixed this week.

**Comment by v1nc3n4** [comment] 2021-02-02 17:02
I need your help again 😞. Can you confirm you can install and run the ARMv8 distribution of Node.js on your workstation? Unfortunately I have no option to verify this distribution on an equivalent architecture.

See https://nodejs.org/en/download/

![node-distro](https://user-images.githubusercontent.com/5869062/106633923-8fa2df80-657f-11eb-8c96-2e7428ca40b4.png)

**Comment by v1nc3n4** [comment] 2021-02-02 17:14
Hmm, now I have a doubt about this architecture. I thought it was simple to deal with. It seems Node.js doesn't provide a compatible build for your system.

For reference: https://github.com/nodejs/build/issues/2474
I must take a look at this problem more deeply.

**Comment by apo1967** [comment] 2021-02-02 17:18
Oh... do you still need me to test the arm binaries?

**Comment by v1nc3n4** [comment] 2021-02-02 17:34
Well no, sorry for the inconvenience 😞.
Of course I'm curious to know if one distribution or the other works on your system. MBP is built over an ARM64 architecture if I understand well, and that may be compatible. But Node's website states the ARMv8 distribution is for Linux. I wonder also if the Mac OS Darwin distribution may work 🤔.
But these considerations are not viable in the long term, and I don't think it's a good idea the plugin tries to use another distribution in the mean time.

**Comment by v1nc3n4** [comment] 2021-02-02 20:00
@apo1967
FYI, if you are just trying to build your project on your workstation, you may install node on your own, using homebrew for example. It seems to be a confirmed workaround. Then, if you set the `nodeDistributionProvided` property to `true`, the plugin can rely on executables found in the PATH, or pick the one located in the directory pointed by the `nodeInstallDirectory` property. The [official documentation](https://siouan.github.io/frontend-gradle-plugin/configuration) shall help you to do that. Feel free to come back here for any news or questions.

**Comment by apo1967** [comment] 2021-02-03 10:46
Thx a lot, this works fine. It also speeds up the build, so it's an improvement actually.

**Comment by v1nc3n4** [comment] 2021-02-14 08:32
Also for reference: https://github.com/nodejs/node/issues/37309

**Comment by v1nc3n4** [comment] 2021-04-20 18:46
Hi all,

As mentioned in Node.js 16.0.0 [release notes](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.0.0), pre-built binaries are now available for Apple Silicon.
Support will be added soon in the plugin.

BR

**Closed** 2021-05-02 09:32 UTC
Labels: Feature

**Comment by v1nc3n4** [comment] 2021-05-02 09:52
Hi @apo1967,

May I ask you to verify if release 5.1.0 allows you to install a Node.js distribution on your MBP?
I don't have such computer by my side, and I would like to have a real feedback about this issue.

Thanks in advance for your help.
BR

**Comment by v1nc3n4** [comment] 2021-05-11 09:25
Hi @apo1967,
Thank you for your help!
This error is expected because the ARM 64 distribution is only available starting from Node.js 16.0.0.
Can you try with this Node.js release?

**Comment by apo1967** [comment] 2021-05-11 09:54
Well, it seems I don't understand what's happening under the hood. I thought the initial problem here was, that there was no M1 compatible node bundle available to pull and execute. So now that there is one, why is the plugin still using an incompatible version?

Anyway, what I did now: I updated the siouan plugin version in my gradle config to 5.1.0, and I updated my local node installation to 16.1.0. Now, when I try to build my frontend app with gradle using the local node installation 16.1.0 the build runs, although now failing due to "unexpected identifier" errors on imported graphql resource files that we're no problem before. If I tell the plugin to not use the local installation, it tries to pull the above mentioned version of node.js (where I had expected it to pull the latest M1 compatible version).

**Comment by v1nc3n4** [comment] 2021-05-11 10:18
> Well, it seems I don't understand what's happening under the hood. I thought the initial problem here was, that there was no M1 compatible node bundle available to pull and execute. So now that there is one, why is the plugin still using an incompatible version?

You're right until the `still using an incompatible version` which sounds weird to me. I may have been a bit fuzzy in my request, so let's explain things in details:
- Your initial problem was the plugin could not download a bundle of Node.js compatible with your M1 workstation.
- Node.js fixed that recently, and now the plugin should be able to download the bundle. But you must upgrade the plugin to version 5.1.0.
- So as the plugin downloads and installs the distribution on its own - which is what I want to verify with your help - you must ensure the `nodeDistributionProvided` property is `false`, and the `nodeVersion` property is at least `16.0.0`.

I didn't expect you upgrade your local installation - I mean any installation you would have done on your own, not with the plugin. I'm sorry if this is what you did.

**Comment by apo1967** [comment] 2021-05-11 11:34
Ok, now I got it. I just forgot about the version number in the gradle settings. So setting this to 16.1.0 the build runs!

**Comment by v1nc3n4** [comment] 2021-05-11 12:05
Thank you very much again for your help on this issue. Have a good day!
BR
